### ISSUE TITLE
Include Account as a dimension

### ISSUE THREAD

**Issue by tarioch** [johannesjh/smart_importer#14]
I have an importer which can return transactions for multiple accounts

e.g.
Assets:Foo:EUR
Assets:Foo:CHF
Assets:Foo:USD

so I can't filter the learning data for the specific account. The predictions should now take the account as an input dimension as it's unlikely that the same transaction that happens for Assets:Foo:EUR would also happen for Assets:Foo:CHF

**Comment by johannesjh** [comment]
looks good. two questions:

1. have you tried if this works with small vocabulary sizes, i.e., when there is only one account?
2. some thoughts on account names should be vectorized? the code currently says `CountVectorizer(ngram_range=(1, 3)`. I expect that this will split each account name into its components, calculate 1-grams, 2-grams and 3-grams from the components, and count their occurrences. Sounds alright to me.

**Comment by tarioch** [comment]
1 I haven't tried yet, probably should solve this generically for all dimensions

2 I didn't do this intentionally, I just copied the payee dimension.     Not sure if this shouldn't be the full account as you quite often have very similar account names with total different meaning.

**Comment by johannesjh** [comment]
> Not sure if this shouldn't be the full account as you quite often have very similar account names with total different meaning.

On the other hand, if a new account name comes along, then machine learning would at least have some knowledge for making its suggestions or predictions.

**Comment by tarioch** [comment]
Ok, going to keep it like I created it and then see how it goes
