### ISSUE TITLE
decorated importer classes do not work in fava

### ISSUE THREAD

**Issue by johannesjh** [johannesjh/smart_importer#29]
decorating importer classes does not work properly in fava.

import.config.py:

```python
CONFIG = [
    bawag_psk.SmartBawagPSKImporter(),
    paylife.SmartPaylifeImporter()
]
```

fava's import page will then show a csv file from paylife as follows:

File | Importer | Account |  [Button] |
-- | -- | -- | --
MeineTransaktionen.csv | smart_importer.predict_postings.PredictPostingsImporter | Liabilities:Mastercard | Extract

Clicking extract triggers the following HTTP request:
```
GET /johannes-ledger-2018/extract/?filename=%2FUsers%2Fjohannes%2FDownloads%2FMeineTransaktionen.csv&importer=smart_importer.predict_postings.PredictPostingsImporter&partial=true HTTP/1.1
```

Problem:
The request should contain the classname of the importer, not of the decorator!

As a result, fava loads the wrong importer (the one for BawagPSK instead of the one for paylife) and produces a runtime exception.

**Comment by yagebu** [comment]
Without having had a look at any of the involved code, I assume this is due to the decorator misbehaving, ie, not using something like https://docs.python.org/3/library/functools.html#functools.wraps or functools.update_wrapper

**Comment by johannesjh** [comment]
thank you, yes that is the problem. Currently, the decorator returns a a subclass of the original importer. The subclass overwrites the extract method. Hence the modified class name of the decorated importer. 

Any ideas how I could patch the importer class (i.e., replace its extract method) while preserving its class name?

**Comment by yagebu** [comment]
> Any ideas how I could patch the importer class (i.e., replace its extract method) while preserving its class name?

Why is the decorator applied to the whole class? Can't it just be a decorator that applies to the extract method if that's all you need to patch?

**Comment by johannesjh** [comment]
The motivation was that this would make it easier to apply the decorator, see #9.

Instead of having to write a custom importer just to be able to apply the decorator, like this:

```python
class MyCustomCSVImporter(CsvImporter):
    @SmartImportDecorator(whatever, arguments)
    def extract(file, existing_entries=None):
        return super().extract(file, existing_entries)

CONFIG = [
    MyCustomCSVImporter(whatever, arguments)
]
```

...it would be more convenient to simply apply the decorator to the whole importer class. This could even be done inline in the import config file, like this:

```python
CONFIG = [
    SmartImportDecorator(CsvImporter(whatever, arguments))
]
```

**Comment by yagebu** [comment]
It might then be easier to implement it as a function decorator and have the class decorator overwrite the extract method instead of subclassing it.

**Comment by johannesjh** [comment]
Update: This task turned out to be more complex than I thought. I have been fighting with nested structures of python decorators. Also with different behaviors depending on how decorators are applied (with or without parentheses, to a class vs to a method). I gave the `wrapt` library a try and also tried a DIY solution. I guess I'll just keep trying.

**Comment by johannesjh** [comment]
Ok, I got it working now. Works in fava, passes all unit tests, merged into master.

**Comment by johannesjh** [comment]
ps
sorry for bypassing the pull request mechanism this time. I could not get the merge working through the web GUI... The problem then turned out to be simply that my github session was expired. Anyway, I pushed the merge into the master branch. All unittests work, my personal importers work, and @tarioch I hope it will also work fine for you!

**Comment by tarioch** [comment]
Works for me without change :) I'm not using them as annotations but instead instantiate them manually in my import.config

**Comment by johannesjh** [comment]
ok great, thank you for the feedback!
