### ISSUE TITLE
limit predictions to missing second postings

### ISSUE THREAD

**Issue by johannesjh** [johannesjh/smart_importer#4]
the `predict_postings` decorator should only predict missing second postings, as opposed to predicting third and fourth postings etc as well, which does not make sense for any usecase i can think of.

**Comment by tarioch** [comment]
Starting to look at this, right now with a simple implementation by letting it be predicted but not adding it to the result. One thing to note is that this also points out that it never makes sense to have predict + suggestion enabled. If you predict then a second posting will be added and therefore there will be no suggestions (correctly).

So i think either you predict or you suggest but never both.

**Comment by johannesjh** [comment]
Prediction plus suggestions can be useful in the following scenario: 

- The importer produces predicted postings. 
- The user may find they need to edit the prediction because it was incorrect. 
- The UI (e.g. of fava) can enhance the editing of postings using these suggestions, e.g., by populating a dropdown list with the suggestions.

**Comment by johannesjh** [comment]
Also, I would argue that suggestions are useful no matter how many postings exist in the imported data, because the suggestions can support editing.

**Comment by tarioch** [comment]
I see that case, to simplify things I would only take the account of the first posting as input for the suggestions, which I think is the current implementation. So I'll just revert the changes I did on the suggestion part.

**Comment by tarioch** [comment]
Another thing which comes to mind. Is there a confidence for the prediction? Because if that one is very low I would rather not have a prediction.

**Comment by johannesjh** [comment]
> I see that case, to simplify things I would only take the account of the first posting as input for the suggestions, which I think is the current implementation. 

Yes, and that should be sufficient for most usecases. (I think that most importers will only output one posting per transaction anyway, each with the same account).

Note: The `pipeline.fit` step does learn from _all_ postings in the training data, hence the conversion from `Transaction` to `TxnPosting` in `predict_postings.py` lines 78ff.  But the subsequent `pipeline.predict` step only uses the first posting's data, hence no use of `TxnPosting` objects in `self.pipeline.predict(transactions)`  in line 147.

**Comment by johannesjh** [comment]
> Another thing which comes to mind. Is there a confidence for the prediction? Because if that one is very low I would rather not have a prediction.

Good point. The decorator could accept a parameter through which users can set a threshold.

The SVM classifier in scikit-learn can calculate probabilities, compare [How to get a classifier's confidence score for a prediction in sklearn?](https://stackoverflow.com/questions/31129592/how-to-get-a-classifiers-confidence-score-for-a-prediction-in-sklearn) on stackoverflow. I don't know how much this will slow down the `pipeline.fit` method, but I would not worry too much about it.
