### ISSUE TITLE
Support existing entries as training data

### ISSUE THREAD

**Issue by tarioch** [johannesjh/smart_importer#8]
Very recently, the ImporterProtocol has been extended to pass the existing transactions in.
It would be great to simply use this instead of specifying explicit training data.

**Comment by johannesjh** [comment]
thank you for the pull request to this ticket! 

to simplify collaboration: do you want commit access in this repository? my impression is that we have very similar goals for the project, right? (namely, as I would put it: to develop this code far enough to be useful for a broad audience, ultimately aiming at making machine learning and smart predictions an official feature of beancount importers that is also supported by fava).

**Comment by tarioch** [comment]
That would be great. Yes I think we have the same goals for this project.

**Comment by johannesjh** [comment]
ok, I added you as collaborator
